<?php
//thePressureRegulationSystem
//$k="<script>document.write(objectRegutalation.ratio);</script>";
//$T="<script>document.write(objectRegutalation.standing);</script>";
//$t="<script>document.write(objectRegutalation.delay);</script>";
//$Kp="<script>document.write(Kp);</script>";
//$Kin="<script>document.write(Kint);</script>";
//
//echo();